export const MESSAGES_TO_RENDER = 75
export const UNREAD_MESSAGES_TO_RENDER = 50
export const MESSAGES_TO_LOAD = 150
export const CONTACTS_TO_LOAD = 20
export const INPUT_MESSAGE_MAX_HEIGHT = 199
export const MESSAGE_LINE_HEIGHT = 25
